### ISSUE TITLE
DLC-helpers whisker coordinate tracking

### ISSUE THREAD

**Issue by Jelte-dV** [mik-schutte/Microstimulation#1]
Hey dude, was looking through the code with Anthea and found something that might need to be adapted.
The current whisker position is only normalized to the extremes in Y-coords (line 174-175), while it is a 3D movement. I don't think you can properly project this 3D movement onto a 2D space and still retain the same accuracy of tracking (this would then be affected by e.g. whisker length or azimuth).

Willing to think along with how to base relative position on both the Y-coords and the X-coords.
Maybe we can start by figuring out the relations between Y and X to fit a parabolic path (whisking arch) instead of a linear straight path?

Reach out and we'll discuss options :)

**Comment by mik-schutte** [comment]
Currently, not adapted. Plans of discussing this with a whisker tracking panel. (You, me, Marti, Keisuke)
